### ISSUE TITLE
Database setup for ticket system

### ISSUE THREAD

**Issue by Brett-Mulder** [fuas-dverse/ticket-system#4]
# Description
Before we are going to store some data in the database. We need to decide which database we are going to use for the Ticket System.

# Tasks
- [ ] Create small research about open databases (JSON / Document based)
- [ ] Setup new database
- [ ] Think about structure for the schemas
- [ ] Vector Database??!

# Definition of done
- A researched database is setup and ready to use

# Links
-
